import type { InstantJobFormData } from "@/types";

export const DEFAULT_INSTANT_FORM: InstantJobFormData = {
  job_title: "",
  department: "",
  job_type: "casual",
  years_of_experience: "",
  experience: [],
  specializations: [],
  job_urgency: "INSTANT",
  description: "",
  responsibilities: [],
  required_skills: [],
  working_conditions: [],
  why_join: [],
  status: "OPEN",
  no_of_hires_required: "1",
  start_date: undefined,
  end_date: undefined,
  check_in_time: "",
  check_out_time: "",
  break_duration_minutes: 0,
  neighborhood_name: "",
  neighborhood_type: "",
  direct_number: "",
  street: "",
  postal_code: "",
  province: "",
  city: "",
  country: "Canada",
};
