import { CandidateDetailsResponse } from "@/stores/api/recruiter-job-api";

import { CandidateListItem } from "@/stores/api/recruiter-job-api";

export const STATIC_CANDIDATE: CandidateDetailsResponse = {
  id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  first_name: "Michael",
  last_name: "Liam",
  full_name: "Michael Liam",
  gender: "Male",
  dob: "1992-05-14",
  profile_image_url: "/icon/card-doctor.svg",
  street: "123 Maple Street",
  street_2: null,
  city: "Toronto",
  state: "Ontario",
  postal_code: "M5H 2N2",
  medical_industry: "Nursing",
  specialty: "Registered Nurse",           // ✅ string, not array
  work_eligibility: "Canadian Citizen",
  expected_salary: "$85,000",
  expected_hour_rate: "$42",
  skill: JSON.stringify([                  // ✅ stored as JSON string
    "Patient Assessment",
    "IV Therapy",
    "Wound Care",
    "Medication Administration",
    "Critical Thinking",
    "EMR Systems",
  ]),
  job_type: "Part Time",
  preferred_location: "Toronto, Ontario",
  preferred_shift: "Morning Shift",
  status: "active",
  completion_percentage: 85,
  email: "michael.liam@example.com",
  phone_number: "+1 123 456 7890",

  // ✅ Correct shape — only id, title, company
  work_experiences: [
    { id: "we1", title: "Registered Nurse",  company: "Toronto General Hospital" },
    { id: "we2", title: "Junior Nurse",       company: "KeRaeva Health"           },
    { id: "we3", title: "Nursing Intern",     company: "Mount Sinai Hospital"     },
  ],

  // ✅ Correct shape — only id, school, degree
  educations: [
    { id: "ed1", school: "Canadian Red Cross University", degree: "Master Degree · MD"           },
    { id: "ed2", school: "University of Toronto",         degree: "Bachelor of Science · Nursing" },
  ],

  // ✅ Correct shape — id, award_name, award_date
  awards: [
    { id: "aw1", award_name: "John McCrae Memorial Medal",    award_date: "Jan 2025" },
    { id: "aw2", award_name: "Excellence in Patient Care Award", award_date: "Mar 2024" },
  ],

  // ✅ Correct shape — id, social_media, link
  social_links: [
    { id: "sl1", social_media: "LinkedIn", link: "https://www.linkedin.com/in/michael-liam"       },
    { id: "sl2", social_media: "LinkedIn", link: "https://www.linkedin.com/in/michael-liam-nurse" },
  ],

  // ✅ Correct shape — id, document_type, title, file_url
  documents: [
    { id: "doc1", document_type: "resume",      title: "Resume",      file_url: null },
    { id: "doc2", document_type: "license",     title: "License",     file_url: null },
    { id: "doc3", document_type: "medical",     title: "Medical",     file_url: null },
    { id: "doc4", document_type: "certificate", title: "Certificate", file_url: null },
  ],

  created_at: "2024-01-15T10:00:00Z",
  updated_at: "2025-04-01T08:30:00Z",
};

export const STATIC_PERFORMANCE = {
  conversational: {
    score: 80,
    metrics: [
      { label: "Live Face Match",       value: 95 },
      { label: "Communication Skills",  value: 25 },
      { label: "Confidence",            value: 82 },
      { label: "Behavioral Signals",    value: 87 },
      { label: "Accuracy of Answers",   value: 87 },
    ],
    strength: "Strong communication presence and high face-match accuracy indicate excellent in-person reliability.",
  },
  behavioral: {
    score: 40,
    metrics: [
      { label: "Live Face Match",       value: 20 },
      { label: "Communication Skills",  value: 25 },
      { label: "Confidence",            value: 32 },
      { label: "Behavioral Signals",    value: 10 },
      { label: "Accuracy of Answers",   value: 40 },
    ],
    strength: "Shows potential in accuracy of answers with room to improve behavioral consistency.",
  },
  communication: {
    score: 58,
    metrics: [
      { label: "Live Face Match",       value: 95 },
      { label: "Communication Skills",  value: 25 },
      { label: "Confidence",            value: 82 },
      { label: "Behavioral Signals",    value: 87 },
      { label: "Accuracy of Answers",   value: 87 },
    ],
    strength: "Balanced communicator with strong technical language usage in clinical contexts.",
  },
  accuracy: {
    score: 88,
    metrics: [
      { label: "Live Face Match",       value: 95 },
      { label: "Communication Skills",  value: 25 },
      { label: "Confidence",            value: 82 },
      { label: "Behavioral Signals",    value: 87 },
      { label: "Accuracy of Answers",   value: 87 },
    ],
    strength: "Highly accurate in clinical knowledge — top 10% among all interviewed candidates.",
  },
};


export const STATIC_CANDIDATES: CandidateListItem[] = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    first_name: "Michael",
    last_name: "Liam",
    full_name: "Michael Liam",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Toronto",
    state: "Ontario",
    postal_code: "M5H 2N2",
    medical_industry: "Nursing",
    specialty: ["Registered Nurse", "ICU Care"],
    role: ["Registered Nurse"],
    availability: [],
    work_permit: "Canadian Citizen",
    job_titles: ["Registered Nurse"],
    preferred_shift: ["Morning"],
    work_eligibility: "Canadian Citizen",
    status: "active",
    completion_percentage: "85",
    email: "michael.liam@example.com",
    phone_number: "+1 123 456 7890",
    highest_interview_score: 88,
    highest_job_interview_score: 88,
  },
  {
    id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    first_name: "Sarah",
    last_name: "Johnson",
    full_name: "Sarah Johnson",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Vancouver",
    state: "British Columbia",
    postal_code: "V6B 1A1",
    medical_industry: "Disability",
    specialty: ["Licensed Practical Nurse", "Wound Care"],
    role: ["Licensed Practical Nurse"],
    availability: [],
    work_permit: "Canadian Citizen",
    job_titles: ["Licensed Practical Nurse"],
    preferred_shift: ["Night"],
    work_eligibility: "Canadian Citizen",
    status: "active",
    completion_percentage: "90",
    email: "sarah.johnson@example.com",
    phone_number: "+1 234 567 8901",
    highest_interview_score: 72,
    highest_job_interview_score: 72,
  },
  {
    id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    first_name: "David",
    last_name: "Kim",
    full_name: "David Kim",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Calgary",
    state: "Alberta",
    postal_code: "T2P 1J9",
    medical_industry: "Disability",
    specialty: ["Support Worker", "Aged Care"],
    role: ["Support Worker"],
    availability: [],
    work_permit: "PR Holder",
    job_titles: ["Support Worker"],
    preferred_shift: ["Evening"],
    work_eligibility: "PR Holder",
    status: "active",
    completion_percentage: "70",
    email: "david.kim@example.com",
    phone_number: "+1 345 678 9012",
    highest_interview_score: 48,
    highest_job_interview_score: 48,
  },
  {
    id: "d4e5f6a7-b8c9-0123-defa-234567890123",
    first_name: "Emma",
    last_name: "Clarke",
    full_name: "Emma Clarke",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Ottawa",
    state: "Ontario",
    postal_code: "K1A 0A9",
    medical_industry: "Nursing",
    specialty: ["Registered Nurse", "Pediatric Nursing"],
    role: ["Registered Nurse"],
    availability: [],
    work_permit: "Canadian Citizen",
    job_titles: ["Registered Nurse"],
    preferred_shift: ["Morning"],
    work_eligibility: "Canadian Citizen",
    status: "active",
    completion_percentage: "78",
    email: "emma.clarke@example.com",
    phone_number: "+1 456 789 0123",
    highest_interview_score: 63,
    highest_job_interview_score: 63,
  },
  {
    id: "e5f6a7b8-c9d0-1234-efab-345678901234",
    first_name: "James",
    last_name: "Walker",
    full_name: "James Walker",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Montreal",
    state: "Quebec",
    postal_code: "H2Y 1C6",
    medical_industry: "Nursing",
    specialty: ["Registered Nurse", "Emergency Care"],
    role: ["Registered Nurse"],
    availability: [],
    work_permit: "Canadian Citizen",
    job_titles: ["Registered Nurse"],
    preferred_shift: ["Morning"],
    work_eligibility: "Canadian Citizen",
    status: "active",
    completion_percentage: "95",
    email: "james.walker@example.com",
    phone_number: "+1 567 890 1234",
    highest_interview_score: 91,
    highest_job_interview_score: 91,
  },
  {
    id: "f6a7b8c9-d0e1-2345-fabc-456789012345",
    first_name: "Olivia",
    last_name: "Brown",
    full_name: "Olivia Brown",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Toronto",
    state: "Ontario",
    postal_code: "M4B 1B3",
    medical_industry: "Nursing",
    specialty: ["Registered Nurse", "Mental Health"],
    role: ["Registered Nurse"],
    availability: [],
    work_permit: "Canadian Citizen",
    job_titles: ["Registered Nurse"],
    preferred_shift: ["Night"],
    work_eligibility: "Canadian Citizen",
    status: "active",
    completion_percentage: "80",
    email: "olivia.brown@example.com",
    phone_number: "+1 678 901 2345",
    highest_interview_score: 55,
    highest_job_interview_score: 55,
  },
  {
    id: "a7b8c9d0-e1f2-3456-abcd-567890123456",
    first_name: "Noah",
    last_name: "Davis",
    full_name: "Noah Davis",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Edmonton",
    state: "Alberta",
    postal_code: "T5J 0N3",
    medical_industry: "Disability",
    specialty: ["Support Worker", "Rehab Care"],
    role: ["Support Worker"],
    availability: [],
    work_permit: "Work Permit",
    job_titles: ["Support Worker"],
    preferred_shift: ["Evening"],
    work_eligibility: "Work Permit",
    status: "active",
    completion_percentage: "65",
    email: "noah.davis@example.com",
    phone_number: "+1 789 012 3456",
    highest_interview_score: 77,
    highest_job_interview_score: 77,
  },
  {
    id: "b8c9d0e1-f2a3-4567-bcde-678901234567",
    first_name: "Sophia",
    last_name: "Martinez",
    full_name: "Sophia Martinez",
    profile_image_url: "/icon/card-doctor.svg",
    city: "Winnipeg",
    state: "Manitoba",
    postal_code: "R3C 0V8",
    medical_industry: "Nursing",
    specialty: ["Registered Nurse", "ICU Care"],
    role: ["Registered Nurse"],
    availability: [],
    work_permit: "Canadian Citizen",
    job_titles: ["Registered Nurse"],
    preferred_shift: ["Morning"],
    work_eligibility: "Canadian Citizen",
    status: "active",
    completion_percentage: "88",
    email: "sophia.martinez@example.com",
    phone_number: "+1 890 123 4567",
    highest_interview_score: 84,
    highest_job_interview_score: 84,
  },
];

// constants/staticData.ts — add this

export const STATIC_CANDIDATES_MAP: Record<string, CandidateDetailsResponse> = {
  [STATIC_CANDIDATE.id]: STATIC_CANDIDATE,
  // For the other 7, clicking them will use STATIC_CANDIDATE as profile fallback
  "b2c3d4e5-f6a7-8901-bcde-f12345678901": { ...STATIC_CANDIDATE, id: "b2c3d4e5-f6a7-8901-bcde-f12345678901", first_name: "Sarah",  last_name: "Johnson",  full_name: "Sarah Johnson"  },
  "c3d4e5f6-a7b8-9012-cdef-123456789012": { ...STATIC_CANDIDATE, id: "c3d4e5f6-a7b8-9012-cdef-123456789012", first_name: "David",  last_name: "Kim",      full_name: "David Kim"      },
  "d4e5f6a7-b8c9-0123-defa-234567890123": { ...STATIC_CANDIDATE, id: "d4e5f6a7-b8c9-0123-defa-234567890123", first_name: "Emma",   last_name: "Clarke",   full_name: "Emma Clarke"    },
  "e5f6a7b8-c9d0-1234-efab-345678901234": { ...STATIC_CANDIDATE, id: "e5f6a7b8-c9d0-1234-efab-345678901234", first_name: "James",  last_name: "Walker",   full_name: "James Walker"   },
  "f6a7b8c9-d0e1-2345-fabc-456789012345": { ...STATIC_CANDIDATE, id: "f6a7b8c9-d0e1-2345-fabc-456789012345", first_name: "Olivia", last_name: "Brown",    full_name: "Olivia Brown"   },
  "a7b8c9d0-e1f2-3456-abcd-567890123456": { ...STATIC_CANDIDATE, id: "a7b8c9d0-e1f2-3456-abcd-567890123456", first_name: "Noah",   last_name: "Davis",    full_name: "Noah Davis"     },
  "b8c9d0e1-f2a3-4567-bcde-678901234567": { ...STATIC_CANDIDATE, id: "b8c9d0e1-f2a3-4567-bcde-678901234567", first_name: "Sophia", last_name: "Martinez", full_name: "Sophia Martinez"},
};