import type { Metadata, Viewport } from "next";
import "./globals.css";
import { fonts } from "@/lib/font";
import ClientLayout from "./client-layout";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Recruiter Portal",
  description: "Generated by create next app",
};

// ✅ THIS is what's been missing the entire time
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={fonts}>
      <body className="font-sans bg-[#F7F5F1]">
        <ClientLayout>{children}</ClientLayout>
        <Analytics />
      </body>
    </html>
  );
}