import type { JobsListResponse } from '@/Interface/job.types';

type JobListItem = JobsListResponse['data']['jobs'][0];

export const DUMMY_JOBS: JobListItem[] = [
  // ── Urgent + OPEN
  {
    id: 'aaa-urgent-open-001',
    job_title: 'Registered Nurse (RN)',
    job_urgency: 'instant',
    status: 'OPEN',
    department: 'Nursing',
    job_type: 'Part-Time',
    years_of_experience: '3-5',
    city: 'Toronto',
    province: 'ON',
    street: '123 Main St',
    pay_range_min: 50,
    pay_range_max: 70,
    specializations: ['ICU', 'Emergency'],
    qualifications: ['BScN'],
    application_count: 4,
    ai_interview: false,
    start_date: '2026-04-12',
    end_date: '2026-04-23',
    check_in_time: '20:00',
    check_out_time: '03:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'aaa-urgent-open-002',
    job_title: 'Home Care Aide',
    job_urgency: 'instant',
    status: 'OPEN',
    department: 'Home Care',
    job_type: 'Casual',
    years_of_experience: '1-2',
    city: 'Vancouver',
    province: 'BC',
    street: '456 Oak Ave',
    pay_range_min: 40,
    pay_range_max: 55,
    specializations: ['Home Care'],
    qualifications: ['PSW'],
    application_count: 2,
    ai_interview: false,
    start_date: '2026-04-12',
    end_date: '2026-04-23',
    check_in_time: '08:00',
    check_out_time: '16:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'aaa-urgent-open-003',
    job_title: 'Licensed Practical Nurse (LPN)',
    job_urgency: 'instant',
    status: 'OPEN',
    department: 'Nursing',
    job_type: 'Full-Time',
    years_of_experience: '2-4',
    city: 'Calgary',
    province: 'AB',
    street: '789 Elm Rd',
    pay_range_min: 45,
    pay_range_max: 60,
    specializations: ['Pediatrics'],
    qualifications: ['LPN Diploma'],
    application_count: 6,
    ai_interview: true,
    start_date: '2026-04-13',
    end_date: '2026-04-30',
    check_in_time: '07:00',
    check_out_time: '15:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── Regular + OPEN
  {
    id: 'bbb-regular-open-001',
    job_title: 'Registered Nurse (RN)',
    job_urgency: 'normal',
    status: 'OPEN',
    department: 'Nursing',
    job_type: 'Full-Time',
    years_of_experience: '5-7',
    city: 'Toronto',
    province: 'ON',
    street: '10 King St',
    pay_range_min: 60,
    pay_range_max: 80,
    specializations: ['Cardiology'],
    qualifications: ['BScN', 'CCRN'],
    application_count: 12,
    ai_interview: true,
    start_date: null,
    end_date: null,
    check_in_time: null,
    check_out_time: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'bbb-regular-open-002',
    job_title: 'Medical Laboratory Technician',
    job_urgency: 'normal',
    status: 'OPEN',
    department: 'Laboratory',
    job_type: 'Part-Time',
    years_of_experience: '2-3',
    city: 'Ottawa',
    province: 'ON',
    street: '22 Bank St',
    pay_range_min: 35,
    pay_range_max: 50,
    specializations: ['Pathology'],
    qualifications: ['MLT Diploma'],
    application_count: 3,
    ai_interview: false,
    start_date: null,
    end_date: null,
    check_in_time: null,
    check_out_time: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'bbb-regular-open-003',
    job_title: 'Physiotherapist',
    job_urgency: 'normal',
    status: 'OPEN',
    department: 'Rehabilitation',
    job_type: 'Full-Time',
    years_of_experience: '4-6',
    city: 'Montreal',
    province: 'QC',
    street: '55 Rue Peel',
    pay_range_min: 55,
    pay_range_max: 75,
    specializations: ['Orthopaedics'],
    qualifications: ['BScPT'],
    application_count: 8,
    ai_interview: true,
    start_date: null,
    end_date: null,
    check_in_time: null,
    check_out_time: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── Regular + CLOSED
  {
    id: 'ccc-regular-closed-001',
    job_title: 'Registered Nurse (RN)',
    job_urgency: 'normal',
    status: 'CLOSED',
    department: 'Nursing',
    job_type: 'Full-Time',
    years_of_experience: '5-7',
    city: 'Toronto',
    province: 'ON',
    street: '10 King St',
    pay_range_min: 60,
    pay_range_max: 80,
    specializations: ['ICU'],
    qualifications: ['BScN'],
    application_count: 24,
    ai_interview: false,
    start_date: null,
    end_date: null,
    check_in_time: null,
    check_out_time: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ccc-urgent-closed-002',
    job_title: 'Emergency Room Nurse',
    job_urgency: 'instant',
    status: 'CLOSED',
    department: 'Emergency',
    job_type: 'Casual',
    years_of_experience: '3-5',
    city: 'Edmonton',
    province: 'AB',
    street: '99 Jasper Ave',
    pay_range_min: 65,
    pay_range_max: 85,
    specializations: ['Emergency'],
    qualifications: ['BScN', 'ACLS'],
    application_count: 4,
    ai_interview: false,
    start_date: '2026-03-05',
    end_date: '2026-03-20',
    check_in_time: '20:00',
    check_out_time: '08:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── PAUSED (Completed)
  {
    id: 'ddd-regular-paused-001',
    job_title: 'Registered Nurse (RN)',
    job_urgency: 'normal',
    status: 'PAUSED',
    department: 'Nursing',
    job_type: 'Part-Time',
    years_of_experience: '2-4',
    city: 'Toronto',
    province: 'ON',
    street: '10 King St',
    pay_range_min: 50,
    pay_range_max: 65,
    specializations: ['Oncology'],
    qualifications: ['BScN'],
    application_count: 2,
    ai_interview: false,
    start_date: '2026-02-01',
    end_date: '2026-02-28',
    check_in_time: '20:00',
    check_out_time: '03:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ddd-urgent-paused-002',
    job_title: 'ICU Nurse',
    job_urgency: 'instant',
    status: 'PAUSED',
    department: 'Intensive Care',
    job_type: 'Full-Time',
    years_of_experience: '5-8',
    city: 'Toronto',
    province: 'ON',
    street: '200 University Ave',
    pay_range_min: 75,
    pay_range_max: 95,
    specializations: ['ICU', 'Critical Care'],
    qualifications: ['BScN', 'CCRN'],
    application_count: 2,
    ai_interview: true,
    start_date: '2026-01-15',
    end_date: '2026-02-15',
    check_in_time: '19:00',
    check_out_time: '07:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── DRAFT (Upcoming)
  {
    id: 'eee-regular-draft-001',
    job_title: 'Occupational Therapist',
    job_urgency: 'normal',
    status: 'DRAFT',
    department: 'Rehabilitation',
    job_type: 'Full-Time',
    years_of_experience: '3-5',
    city: 'Winnipeg',
    province: 'MB',
    street: '300 Portage Ave',
    pay_range_min: 50,
    pay_range_max: 70,
    specializations: ['Geriatrics'],
    qualifications: ['BScOT'],
    application_count: 0,
    ai_interview: false,
    start_date: null,
    end_date: null,
    check_in_time: null,
    check_out_time: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'eee-urgent-draft-002',
    job_title: 'Respiratory Therapist',
    job_urgency: 'instant',
    status: 'DRAFT',
    department: 'Respiratory',
    job_type: 'Casual',
    years_of_experience: '2-4',
    city: 'Halifax',
    province: 'NS',
    street: '5 Spring Garden Rd',
    pay_range_min: 45,
    pay_range_max: 60,
    specializations: ['Pulmonology'],
    qualifications: ['RRT'],
    application_count: 0,
    ai_interview: false,
    start_date: '2026-05-05',
    end_date: '2026-05-25',
    check_in_time: '06:00',
    check_out_time: '18:00',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Client-side filter to mimic backend filtering
export function filterDummyJobs(params: {
  joburgency?: 'instant' | 'normal';
  status?: 'DRAFT' | 'OPEN' | 'PAUSED' | 'CLOSED';
  page?: number;
  limit?: number;
}): { jobs: JobListItem[]; total: number; totalPages: number } {
  let filtered = [...DUMMY_JOBS];

  if (params.joburgency) {
    filtered = filtered.filter((j) => j.job_urgency === params.joburgency);
  }
  if (params.status) {
    filtered = filtered.filter((j) => j.status === params.status);
  }

  const page       = params.page  ?? 1;
  const limit      = params.limit ?? 10;
  const total      = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / limit));
  const offset     = (page - 1) * limit;
  const jobs       = filtered.slice(offset, offset + limit);

  return { jobs, total, totalPages };
}